const POPUP_TYPES = {
  API_ERROR: "API_ERROR",
  BASIC: "BASIC",
  TEXTS: "TEXTS",
  MEDIA: "MEDIA",
  EDIT_GENERAL_INFO: "EDIT_GENERAL_INFO",
  GENERAL_INFO: "GENERAL_INFO",
  LINKS: "LINKS",
  META_TAGS: "META_TAGS",
  LEAD_SENT_SUCCESS: "LEAD_SENT_SUCCESS",
};

export default POPUP_TYPES;
